"""
services/investigation/profile_registry.py

Static configuration-driven Investigation Profile Registry.

Each profile maps an AttackHypothesisType to an InvestigationProfile
that declares which tools are mandatory / optional / expensive.

DESIGN RULES:
    - All 13 attack hypothesis types must have a profile.
    - Tool names are stable string identifiers from the Tool Registry.
    - Do NOT execute tools here. This is metadata only.
    - Profiles are consumed by profile_selector (policy engine).
    - Profiles must not be generated by an LLM.
    - Adding a new profile requires updating this file, not dynamic code.

TOOL NAME CONVENTIONS:
    Tool names match keys in TOOL_REGISTRY (tool_registry.py).
    They are stable identifiers — never generate them from email content.
"""

from __future__ import annotations

from app.contracts.investigation import AttackHypothesisType, InvestigationLevel
from app.contracts.policy import InvestigationProfile

# ---------------------------------------------------------------------------
# Tool name constants — single source of truth to prevent typos
# ---------------------------------------------------------------------------
# Level 0 tools (deterministic, no external calls)
T_SPF_DKIM_DMARC = "spf_dkim_dmarc"
T_HEADER_PARSE = "header_parse"
T_RELAY_RECONSTRUCTION = "relay_reconstruction"
T_DETERMINISTIC_HEURISTICS = "deterministic_heuristics"

# Level 1 tools (targeted ML, no external calls)
T_URL_ML = "url_ml"
T_HEADER_ML = "header_ml"
T_nlp_intent_ml = "nlp_intent_ml"
T_HTML_ANALYSIS = "html_analysis"
T_ATTACHMENT_STATIC_ANALYSIS = "attachment_static_analysis"

# Level 2 tools (external enrichment)
T_DOMAIN_INTELLIGENCE = "domain_intelligence"
T_URL_REPUTATION = "url_reputation"
T_IP_INTELLIGENCE = "ip_intelligence"
T_SENDER_HISTORY = "sender_history"
T_HISTORICAL_CORRELATION = "historical_correlation"
T_RDAP_DOMAIN = "rdap_domain"

# Level 3 tools (Groq — NOT used in Stage 1, contract only)
T_GROQ_REASONING = "groq_reasoning"


# ---------------------------------------------------------------------------
# Profile Registry
# ---------------------------------------------------------------------------

INVESTIGATION_PROFILES: dict[AttackHypothesisType, InvestigationProfile] = {

    AttackHypothesisType.CREDENTIAL_PHISHING: InvestigationProfile(
        profile_id="credential_phishing",
        hypothesis_type=AttackHypothesisType.CREDENTIAL_PHISHING,
        mandatory_tools=[T_URL_ML, T_HTML_ANALYSIS, T_DETERMINISTIC_HEURISTICS],
        optional_tools=[T_DOMAIN_INTELLIGENCE, T_URL_REPUTATION],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.BEC: InvestigationProfile(
        profile_id="bec",
        hypothesis_type=AttackHypothesisType.BEC,
        mandatory_tools=[T_HEADER_PARSE, T_nlp_intent_ml, T_DETERMINISTIC_HEURISTICS],
        optional_tools=[T_SENDER_HISTORY, T_DOMAIN_INTELLIGENCE],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.EXECUTIVE_IMPERSONATION: InvestigationProfile(
        profile_id="executive_impersonation",
        hypothesis_type=AttackHypothesisType.EXECUTIVE_IMPERSONATION,
        mandatory_tools=[T_HEADER_PARSE, T_nlp_intent_ml, T_DETERMINISTIC_HEURISTICS],
        optional_tools=[T_SENDER_HISTORY, T_DOMAIN_INTELLIGENCE],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.VENDOR_FRAUD: InvestigationProfile(
        profile_id="vendor_fraud",
        hypothesis_type=AttackHypothesisType.VENDOR_FRAUD,
        mandatory_tools=[T_HEADER_PARSE, T_nlp_intent_ml, T_DETERMINISTIC_HEURISTICS],
        optional_tools=[T_SENDER_HISTORY, T_DOMAIN_INTELLIGENCE, T_RDAP_DOMAIN],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.PAYMENT_DIVERSION: InvestigationProfile(
        profile_id="payment_diversion",
        hypothesis_type=AttackHypothesisType.PAYMENT_DIVERSION,
        mandatory_tools=[T_HEADER_PARSE, T_nlp_intent_ml, T_DETERMINISTIC_HEURISTICS],
        optional_tools=[T_SENDER_HISTORY, T_DOMAIN_INTELLIGENCE],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.INVOICE_FRAUD: InvestigationProfile(
        profile_id="invoice_fraud",
        hypothesis_type=AttackHypothesisType.INVOICE_FRAUD,
        mandatory_tools=[T_HEADER_PARSE, T_nlp_intent_ml, T_DETERMINISTIC_HEURISTICS],
        optional_tools=[T_SENDER_HISTORY, T_DOMAIN_INTELLIGENCE],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.MALICIOUS_URL: InvestigationProfile(
        profile_id="malicious_url",
        hypothesis_type=AttackHypothesisType.MALICIOUS_URL,
        mandatory_tools=[T_URL_ML, T_HTML_ANALYSIS],
        optional_tools=[T_URL_REPUTATION, T_DOMAIN_INTELLIGENCE],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.MALWARE_DELIVERY: InvestigationProfile(
        profile_id="malware_delivery",
        hypothesis_type=AttackHypothesisType.MALWARE_DELIVERY,
        mandatory_tools=[T_ATTACHMENT_STATIC_ANALYSIS],
        optional_tools=[T_URL_ML, T_URL_REPUTATION],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.MALICIOUS_ATTACHMENT: InvestigationProfile(
        profile_id="malicious_attachment",
        hypothesis_type=AttackHypothesisType.MALICIOUS_ATTACHMENT,
        mandatory_tools=[T_ATTACHMENT_STATIC_ANALYSIS],
        optional_tools=[T_URL_ML],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.SPOOFING: InvestigationProfile(
        profile_id="spoofing",
        hypothesis_type=AttackHypothesisType.SPOOFING,
        mandatory_tools=[T_SPF_DKIM_DMARC, T_RELAY_RECONSTRUCTION, T_HEADER_PARSE],
        optional_tools=[T_IP_INTELLIGENCE, T_SENDER_HISTORY],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.COMPROMISED_ACCOUNT: InvestigationProfile(
        profile_id="compromised_account",
        hypothesis_type=AttackHypothesisType.COMPROMISED_ACCOUNT,
        mandatory_tools=[T_SPF_DKIM_DMARC, T_HEADER_PARSE, T_RELAY_RECONSTRUCTION],
        optional_tools=[T_SENDER_HISTORY, T_IP_INTELLIGENCE],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.SOCIAL_ENGINEERING: InvestigationProfile(
        profile_id="social_engineering",
        hypothesis_type=AttackHypothesisType.SOCIAL_ENGINEERING,
        mandatory_tools=[T_nlp_intent_ml, T_DETERMINISTIC_HEURISTICS],
        optional_tools=[T_SENDER_HISTORY, T_DOMAIN_INTELLIGENCE],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),

    AttackHypothesisType.CAMPAIGN: InvestigationProfile(
        profile_id="campaign",
        hypothesis_type=AttackHypothesisType.CAMPAIGN,
        mandatory_tools=[T_HEADER_PARSE, T_RELAY_RECONSTRUCTION],
        optional_tools=[T_IP_INTELLIGENCE, T_DOMAIN_INTELLIGENCE],
        expensive_tools=[T_HISTORICAL_CORRELATION, T_GROQ_REASONING],
        min_level=InvestigationLevel.L0_TRIAGE,
    ),
}

# Validate all 13 hypothesis types are covered at import time
_COVERED = set(INVESTIGATION_PROFILES.keys())
_REQUIRED = set(AttackHypothesisType)
assert _COVERED == _REQUIRED, (
    f"Profile registry is incomplete. Missing: {_REQUIRED - _COVERED}"
)
